dist: trusty
sudo: required

language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: "yopo"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.sonar/cache'

cache:
    directories:
    - bin #cache .weights files
    
# command to install dependencies
install: 
    - pip3 install -r requirements.txt
    - pip3 install -r test/requirements-testing.txt
    - pip3 install -e .

# command to run tests
script:
    - sonar-scanner -X
    - export PYTHONPATH=$PWD
    - python3 test/YOPO/test_calculate_IOU.py
    - pytest -x --cov=./


#Upload code coverage statistics
#after_success:
