dist: trusty
sudo: required

language: python
python:
  - "3.6"

addons:
  sonarcloud:
    organization: "rij12-github"
    token:
      secure: "b7bd23cbad5d2a534003dbdbdecf517265a5e739"

jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'

cache:
    directories:
    - bin #cache .weights files
    
# command to install dependencies
install: 
    - pip3 install -r requirements.txt
    - pip3 install -e .

# command to run tests
script:
    - export PYTHONPATH=$PWD
    - python3 darkflow/net/yopo/tests/test_calculate_IOU.py

#Upload code coverage statistics
after_success:
  - sonar-scanner \
    -Dsonar.projectKey=your_project_key_that_must_be_unique \
    -Dsonar.sources=. \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.organization=your_organization_key \
    -Dsonar.login=abcdef0123456789